name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # または、GitHub Pages にデプロイしたいブランチ名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7  # 最新のバージョンに更新

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3  # 最新のバージョンに更新
        with:
          node-version: '20'  # Node.js 20 を指定

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist  # ビルドされたファイルが出力されるディレクトリ
          cname: ''  # CNAMEファイルが必要な場合は、ドメイン名を指定します。無ければ空のままで大丈夫です
